// Package k8sjobs implements cloud.JobDispatcher using Kubernetes batch/v1 Jobs.
package k8sjobs

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/gambtho/cronfoundry/internal/cloud"
)

var ErrWaitNotImplemented = errors.New("k8sjobs: Wait not implemented: observe via kubectl")
var ErrKillNotImplemented = errors.New("k8sjobs: Kill not implemented: delete Job via kubectl")

// Config holds the static parameters for the K8s Jobs dispatcher.
type Config struct {
	Namespace      string
	RunnerImage    string
	ServiceAccount string // K8s ServiceAccount with workload identity annotation
}

// JobSpec is the neutral shape passed to K8sClient.CreateJob.
type JobSpec struct {
	Namespace      string
	Image          string
	ServiceAccount string
	Args           []string
	Env            []string
	// Name is generated by the dispatcher; callers do not set it.
	Name string
}

// K8sClient is the testability seam over the real Kubernetes client.
type K8sClient interface {
	CreateJob(ctx context.Context, spec JobSpec) error
}

// Dispatcher implements cloud.JobDispatcher using Kubernetes Jobs.
type Dispatcher struct {
	client K8sClient
	cfg    Config
}

// NewDispatcher returns a Dispatcher. Panics if client is nil.
func NewDispatcher(client K8sClient, cfg Config) *Dispatcher {
	if client == nil {
		panic("k8sjobs: NewDispatcher: client must not be nil")
	}
	return &Dispatcher{client: client, cfg: cfg}
}

// Compile-time interface check.
var _ cloud.JobDispatcher = (*Dispatcher)(nil)

// Dispatch creates a K8s Job and returns immediately. The returned Handle
// has PID()=0 and Wait()/Kill() not implemented (observe via kubectl/k8s API).
func (d *Dispatcher) Dispatch(ctx context.Context, req cloud.DispatchRequest) (cloud.Handle, error) {
	name := fmt.Sprintf("cf-runner-%d", time.Now().UnixMilli())
	spec := JobSpec{
		Name:           name,
		Namespace:      d.cfg.Namespace,
		Image:          d.cfg.RunnerImage,
		ServiceAccount: d.cfg.ServiceAccount,
		Args:           append([]string{}, req.Args...),
		Env:            append([]string{}, req.Env...),
	}
	if err := d.client.CreateJob(ctx, spec); err != nil {
		return nil, fmt.Errorf("k8sjobs: dispatch: %w", err)
	}
	return &k8sHandle{}, nil
}

type k8sHandle struct{}

var _ cloud.Handle = (*k8sHandle)(nil)

func (h *k8sHandle) PID() int    { return 0 }
func (h *k8sHandle) Wait() error { return ErrWaitNotImplemented }
func (h *k8sHandle) Kill() error { return ErrKillNotImplemented }
